Add method that deletes product and create the general product set
googleinterns/step62-2020 pull request #13
Opened 2020-07-23 20:20 UTC by PhillipsOlagunju

2020-07-23 20:40 UTC, mrjwashiv requested changes

2020-07-23 20:40 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/servlets/BrowseServlet.java
> +    //   Map<String, List<FileInfo>> files = blobstore.getFileInfos(request);
you can probably delete this

2020-07-23 20:40 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/servlets/ViewProductsServlet.java
> +    //   Map<String, List<FileInfo>> files = blobstore.getFileInfos(request);
Same here

2020-07-23 20:40 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/servlets/CloudVisionServlet.java
>      // String gcsUrl = CloudStorageLibrary.getGcsFilePath(request, blobstore);
Same here

2020-07-23 20:40 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/servlets/CloudVisionServlet.java
>      Map<String, List<FileInfo>> files = blobstore.getFileInfos(request);
You can delete this

2020-07-23 21:09 UTC, mrjwashiv approved these changes

2020-07-24 16:50 UTC, jayspringfield approved these changes
Looks good!

2020-07-24 16:54 UTC, merged