Finish up most of the UI and corresponding servlets
googleinterns/step62-2020 pull request #9
Opened 2020-07-20 20:50 UTC by SirLegolot

This pull request is absolutely massive, but that's because of a couple of things:
- Merges from the master to my branch pull code written by james and phillips. I believe I have merged twice.
- I had to add a library for css tags input. It used to be a link at the top of my html file, but since it was taken down, I had to put a folder with the github repo in the code (+1000 lines or so). There is an MIT License for the code I pulled, so I should be fine. It is under the token-autocomplete-master directory

2020-07-20 20:58 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/data/CloudStorageLibrary.java
> +                return "Siiikee!";
Maybe change this back? I don't think it matters right now tho

2020-07-20 22:00 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/data/CloudStorageLibrary.java
> +                return "Siiikee!";
Maybe change this back, Idk it's up to you, it doesn't really matter anymore

2020-07-20 22:02 UTC, mrjwashiv commented on project/src/test/java/com/google/sps/cloudstoragetests/UploadedFileUrlTest.java
> +        String expected = "Siiikee!";
up to you.

2020-07-20 22:02 UTC, mrjwashiv requested changes
Looks really good, very tiny things

2020-07-21 17:53 UTC, mrjwashiv requested changes

2020-07-21 17:53 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/servlets/BrowseServlet.java
> +    // Creates a new SearchIno object, which will be stored in datastore.
Small typo

2020-07-21 17:53 UTC, mrjwashiv commented on project/src/main/java/com/google/sps/servlets/ViewProductsServlet.java
> +    // Creates a new SearchIno object, which will be stored in datastore.
Same here?

2020-07-21 18:01 UTC, mrjwashiv approved these changes

2020-07-21 20:05 UTC, jayspringfield approved these changes
This all looks fine.  I didn't go over the blobstore stuff since you said this was just a merge of what James already committed.

Your note makes sense but suggests a good way in the future to split up pull requests.  It would be cleaner to have one PR for the CSS library, one for merging James' changes (if possible) and another for what you've added here.  A bunch of small PRs are preferred to a large one since they're easier to review and much easier to understand if you have to trace back through your changes in the future.

2020-07-21 20:05 UTC, jayspringfield commented on project/src/main/java/com/google/sps/data/ServletLibrary.java
> +      System.err.println("ListAllBusinesses: datastore is null!");
How are you able to view this error text?  Phillips wasn't able to see standard output/error so it would help him if you could show him how.

2020-07-21 21:08 UTC, SirLegolot commented on project/src/main/java/com/google/sps/data/ServletLibrary.java
> +      System.err.println("ListAllBusinesses: datastore is null!");
Yeah in deployment, this won't be visible. The best way to actually error report when deploying is throwing a runtime exception. I'll be making a pr that fixes this up, but that's what i told phillips

2020-07-21 21:08 UTC, merged